config/routes.rb
RailsApi::Application.routes.draw do

  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      resources :users, shallow: false do
        resources :checkins, only: [:index, :show, :create, :update, :destroy]
        resources :friendships, only: [:index, :show, :create, :update, :destroy]
      end

      resources :places
      resources :checkins, only: [:index, :show]
      resources :friendships, only: [:index, :show]
    end
  end

  root 'static_pages#home'
  match '/places', to: 'places#index', via: 'get', as: 'places'
  match '/place/:id', to: 'places#show', via: 'get', as: 'place'
  match '/users', to: 'users#index', via: 'get', as: 'users'
  match '/user/:id', to: 'users#show', via: 'get', as: 'user'
  match '/signup', to: 'users#new', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'

end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "RailsApi App", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Places", places_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <li><%#= link_to "Sign in", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>